### ISSUE TITLE
Order for raw CHIRPS data over large region is stuck

### ISSUE THREAD

**Issue by rbavery** [SERVIR/ClimateSERV#5]
I'm curious if the job is going through, since the job ID keeps changing each second. The area is a large portion of France and a bit of Switzerland spanning the Rhone river. When I try to submit the job with the programmatic API I get a 500 internal server error. Here's my code:

```python
import requests as r

poly = {"type":"Polygon",
        "coordinates":[[[4.3121337890625,43.393073720674415],
                        [6.2347412109375,43.393073720674415],
                        [6.2347412109375,46.20644812194458],
                        [4.3121337890625,46.20644812194458],
                        [4.3121337890625,43.393073720674415]
                       ]
                      ]
       }
start_time = "01/01/1981"
end_time = "07/27/2020"

request_str = f"https://climateserv.servirglobal.net/chirps/submitDataRequest/?datatype=0&begintime={start_time}&endtime={end_time}&intervaltype=0&operationtype=5&callback=successCallback&dateType_Category=default&isZip_CurrentDataType=false&geometry={poly}"

response = r.get(request_str)

response.text
```

And the GUI response
![Selection_105](https://user-images.githubusercontent.com/22258697/88591139-bc929a80-d010-11ea-8827-3d98f4314e4f.png)

**Comment by billyz313** [comment]
We seem to have been having some system resource issues.  I also see that your code is sending a python dict instead of json which would cause failures.

I recommend that you use our python ClimateServ API by doing pip install climateserv

Here is some sample code: (Please adjust the OutFile path to an existing directory on ur machine)

```
import climateserv.api

GeometryCoords = [[4.3121337890625,43.393073720674415],[6.2347412109375,43.393073720674415],[6.2347412109375,46.20644812194458],[4.3121337890625,46.20644812194458],[4.3121337890625,43.393073720674415]]

DatasetType = 'CHIRPS'
OperationType = 'Average'
EarliestDate = '01/01/1981'
LatestDate = '07/28/2020'
SeasonalEnsemble = ''
SeasonalVariable = ''
Outfile = 'C:\demo\out2020.csv'

climateserv.api.request_data(DatasetType, OperationType,
             EarliestDate, LatestDate,GeometryCoords,
             SeasonalEnsemble, SeasonalVariable,Outfile)
```

**Comment by rbavery** [comment]
Gotcha, thanks. I need the output in a time series of tifs so I'll wait for the improved region subsetting feature.
